version: "3.7"

services:
  docs-indexer:
    image: docs-indexer
    build:
      context: .
    container_name: docs-indexer
    environment:
    - ELASTICSEARCH_HOST=elasticsearch
    - SLEEP_TIMEOUT=${SLEEP_TIMEOUT}
    volumes:
    - ${LOCAL_ARTICLES_PATH}:/opt/io/docs-indexer/articles
    ports:
    - 8093:8093
    depends_on:
    - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - ${ELASTICSEARCH_DATA}:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    - 9300:9300
